name: Main

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'dev'

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.ci.yml"

      - name: Run linters
        run: docker compose --file docker-compose.ci.yml run --rm webapp task code-lint



   
